// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUtAu4VElNmGSFPeB-nmtEVJdrxLolT8',
    appId: '1:870539036227:web:f8eb623c522b930fe436f6',
    messagingSenderId: '870539036227',
    projectId: 'timebound-ef7e9',
    authDomain: 'timebound-ef7e9.firebaseapp.com',
    storageBucket: 'timebound-ef7e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDjUjvzW3w0pw8ZxPkPOeW8gWK5HRQuo',
    appId: '1:870539036227:android:103aa4e64be850d7e436f6',
    messagingSenderId: '870539036227',
    projectId: 'timebound-ef7e9',
    storageBucket: 'timebound-ef7e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5A4MOi2RvtmEYQHnv7ve4aHwraYAeNaE',
    appId: '1:870539036227:ios:29b867f223ba5504e436f6',
    messagingSenderId: '870539036227',
    projectId: 'timebound-ef7e9',
    storageBucket: 'timebound-ef7e9.firebasestorage.app',
    iosBundleId: 'com.example.timebound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5A4MOi2RvtmEYQHnv7ve4aHwraYAeNaE',
    appId: '1:870539036227:ios:29b867f223ba5504e436f6',
    messagingSenderId: '870539036227',
    projectId: 'timebound-ef7e9',
    storageBucket: 'timebound-ef7e9.firebasestorage.app',
    iosBundleId: 'com.example.timebound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjUtAu4VElNmGSFPeB-nmtEVJdrxLolT8',
    appId: '1:870539036227:web:a8079d43b0a505c1e436f6',
    messagingSenderId: '870539036227',
    projectId: 'timebound-ef7e9',
    authDomain: 'timebound-ef7e9.firebaseapp.com',
    storageBucket: 'timebound-ef7e9.firebasestorage.app',
  );

}